### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [franniee/prj-rev-bwfs-dasmoto#8]
https://github.com/franniee/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20/resources/style.css#L25-L68

You're repeating a lot of styles in these three CSS rules.

When you have some styles that need to get applied to several elements, write them in a single rule with a more general selector. For example:

```css
* {
  font-family: Helvetica;
}

.product h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

#brushes {
  background-color: mediumspringgreen;
}
```
